### ISSUE TITLE
Run /WHO Not-* on connect

### ISSUE THREAD

**Issue by SoniEx2** [notifico/notifico#106]
The bots should run a `/WHO Not-*` on connect. This will only work if #105 is also implemented. (~~altho there seems to be issues with this and charybdis...~~ I was wrong, it's just that `/WHO *` is special cased to do a /WHO on the last channel you joined. PS: this has been a thing since ircd 2.8)

If it fails, which it shouldn't, unless the network is really shit, then... do w/e you want... probably shout at the user, too. (the bots can know it failed because they won't show up, for example doing `/WHO SoniEx*` when I'm connected as SoniEx2 lists me)

Bot verification is another issue, but still simple to do.

**Comment by TkTech** [comment]
Not necessary - the network name can be determined from 005, at which point the manager can look for bots known to be on the same advertised network and PRIVMSG a token between them to consolidate.
