### ISSUE TITLE
bot is dead on #virtkick

### ISSUE THREAD

**Issue by Nowaker** [notifico/notifico#107]
```
17:45:07 -!- Not-7e7f [~notifico@198.199.82.216] has quit [Ping timeout: 265 seconds]
```
New commits to [virtkick-webapp](https://github.com/virtkick/virtkick-webapp/commits/master) didn't revive the bot. 

My profile: http://n.tkte.ch/Nowaker/virtkick-webapp

**Comment by TkTech** [comment]
#112
