### ISSUE TITLE
Support /PASS-protected networks

### ISSUE THREAD

**Issue by SoniEx2** [notifico/notifico#108]
Bouncers more reliable than the target network, rebranding, etc

**Comment by TkTech** [comment]
This feature has been discussed before - it's actually already implemented in the backend and in the message format used to communicate with the bots. It will not be allowed for the publicly hosted instance, but will be able to enable it for your own private instance.

Allowing PASS publicly gives too many ways to hijack the bots identity on too many different networks.

**Comment by Dav1dde** [comment]
Just for reference: #3
