### ISSUE TITLE
bot doesn't connect to my network

### ISSUE THREAD

**Issue by BlackDragonGR** [notifico/notifico#109]
The bot doesn't connect. It was previously connected through another account but now i set it to connect through mine. Can you investigate it or just restart it? Or maybe set an option available to us to restart or force to connect anytime something occurs...

**Comment by BlackDragonGR** [comment]
Anyone can help?

**Comment by GLolol** [comment]
Sometimes notifico doesn't know when it has been disconnected from a network. The problem usually goes away after a while when someone resets the bots or whatever. Lots of issues like this have been opened if you look on the issue tracker.

**Comment by BlackDragonGR** [comment]
Ok, it joined today... Maybe it should have a ping pong request and reconnect ?

**Comment by GLolol** [comment]
Yeah, that would be nice...

**Comment by TkTech** [comment]
@112
