### ISSUE TITLE
notifico has been down since 2015-01-06 19:38:30+0200 on chat.freenode.net +6697

### ISSUE THREAD

**Issue by Mikaela** [notifico/notifico#111]
`2015-01-05.log:[13:36:38] *** Quits: Not-86de (~notifico@198.199.82.216) (*.net *.split)`

Very likely duplicate of #110, #109, #107, #92, but as no one seems to say anything at IRC and everyone just comes to this issue tracker so I thought I could do so too.

**Comment by tterrag1098** [comment]
:+1: Been down for a few days on espernet as well.

**Comment by TkTech** [comment]
#112
