### ISSUE TITLE
Bots have issues on certain networks.

### ISSUE THREAD

**Issue by TkTech** [notifico/notifico#112]
General catch-all ticket.

**Comment by TkTech** [comment]
My personal hosted instance (n.tkte.ch) is currently unavailable due to DNS issues. This will be resolved as soon as possible.

**Comment by TkTech** [comment]
http://n.ein.io/ may be used as an alternative to http://n.tkte.ch for your hooks. Both are backed by the same instances and database.

**Comment by Mikaela** [comment]
https://github.com/notifico/notifico/issues/111 appears to be happening again (down on chat.freenode.net +6697), but I am not sure when it started.

**Comment by Mikaela** [comment]
Notifico missing on chat.freenode.net +6697 possibly starting from today as the last time it was seen was `2015-01-24 23:01:56+0200`.

rajaniemi.freenode.net splitted or something, I am not sure if that is releated.

**Comment by BlackDragonGR** [comment]
Same for me too

**Comment by Mikaela** [comment]
Down on chat.freenode.net +6697. Last seen: 2015-02-08 07:07:41+0200.

```
2015-02-08.log:[07:07:41] *** Quits: Not-f917 (~notifico@198.199.82.216) (Ping timeout: 244 seconds)
```

**Comment by Beliaar** [comment]
Still down on freenode? Not getting notifications in any channel.

**Comment by pjaaskel** [comment]
We at #pocl irc.oftc.net stopped seeing notifications some weeks ago.

**Comment by TkTech** [comment]
The bots have been restarted.

@pjaaskel I see nothing at all for irc.oftc.net in the logs, it looks like oftc.net might have banned them for whatever reason. Will review.

**Comment by Beliaar** [comment]
Seems to be down again on freenode.

**Comment by TkTech** [comment]
@Beliaar They should rejoin on the next notification, sorry about that.

**Comment by pjaaskel** [comment]
Seems to be offline again in oftc.

**Comment by Beliaar** [comment]
In freenode as well.

**Comment by DreadKnight** [comment]
Yeah, not working for me on #AncientBeast (freenode) for a long time now.

**Comment by RoyAwesome** [comment]
Gamesurge bots are having issues
