### ISSUE TITLE
New account.

### ISSUE THREAD

**Issue by Polarcraft** [notifico/notifico#119]
Okay so I just made a notifico account, but the bot has yet to join my channel. Any reason why this is happening?

**Comment by Mikaela** [comment]
What modes do you have on the channel?

* +c prevents formatting from working, but doesn't affect joining
* +S or `+b $~z` requires SSL and the bot might not be using it as it tries grouping connections.
* +r or `+b $~a` requires the bot to be identified to services which it never is.

Also have you committed anything? The bot only appears when it has something to say and disappears some time after that.

**Comment by nyuszika7h** [comment]
@Mikaela It only disappears if there's a ping timeout, netsplit or something.

**Comment by Polarcraft** [comment]
No didn't add anything. Just hasn't joined yet.

**Comment by Mikaela** [comment]
The bot won't join until it has something to announce.

**Comment by Polarcraft** [comment]
As in I make a comment?

**Comment by Mikaela** [comment]
Depending on what you have configured in hook settings at GitHub. By default only commits are announced if I recall correctly.

**Comment by Polarcraft** [comment]
So my problem was my port :( GG.
