### ISSUE TITLE
Breaks on netsplits

### ISSUE THREAD

**Issue by ThePsionic** [notifico/notifico#122]
Yesterday, a netsplit occurred on irc.esper.net and since then none of my commits have been pushed to IRC. This leads me to believe that something goes wrong on the backend when a netsplit occurs. I am using http://n.tkte.ch, not running my own version, so I don't have any error messages and the likes. Checking my repo settings I found out that GitHub still does deliver and Notifico! still does get the push events correctly, they are just not being passed on to IRC.

**Comment by Dav1dde** [comment]
This is a known problem, see #112 - This is hopefully fixed with #120 (this is already merged but not yet live).

**Comment by ThePsionic** [comment]
Ah, thanks for the links to the other issues. Didn't go through the closed issues to see if it was already known, and I hope that #120 goes live soon.
