### ISSUE TITLE
21:33 -!- Not-3656 [~notifico@198.199.82.216] has quit [Remote host closed the connection]

### ISSUE THREAD

**Issue by sunweaver** [notifico/notifico#123]
Hi,

a couple of days ago I set up several hooks for the "ArcticaProject" on http://n.tkte.ch.

Two days ago (2015-05-12) at 21:33 the bot vanished from our #arctica channel on Freenode and has not been seen since then. Although there were some commits on Github.

Any help is highly appreciated.

Mike

**Comment by Dav1dde** [comment]
This is a known problem, see #112, #122 - I was working on a fix for this, see #120, this fix is already merged but not live yet, it will get some real world testing before it is actually live (better to have a pretty good system with a few flaws, then a system which doesn't work at all). But hopefully it will be deployed soon.
