### ISSUE TITLE
HTTP auth on plaintext hooks

### ISSUE THREAD

**Issue by SoniEx2** [notifico/notifico#135]
Can we get HTTP auth on plaintext hooks?

**Comment by Dav1dde** [comment]
What would that accomplish? There is no benefit in HTTP-Auth.

**Comment by SoniEx2** [comment]
Other things such as github hook "secret" could also be used.

Things like this would just make it harder for a spammer to take over a random project's hooks.

**Comment by Dav1dde** [comment]
They don't take over existing hooks, they create new ones.

**Comment by SoniEx2** [comment]
And that part is handled by #136

**Comment by TkTech** [comment]
No benefit. If someone is using your hook, it's because you've posted it somewhere publicly. Using HTTP Auth doesn't change that at all.

It is realistically impossible to brute force the existing /<project_id>/<secret> already.
