### ISSUE TITLE
Notifico refuses to send commits to multiple channels on the same network

### ISSUE THREAD

**Issue by GLolol** [notifico/notifico#141]
For the project http://n.tkte.ch/GLolol/PyLink, I have two channels set up: `#dev` and `#PyLink` on `irc.overdrivenetworks.com`.

However, Notifico will only deliver commit notifications to *one* of the two channels whenever something is done. The Notifico bot will join both channels, but in my case, only sends commits to the first channel, `#dev`.

**Comment by TkTech** [comment]
@GLolol is your second channel blocking messages with colors or unverified users?

**Comment by GLolol** [comment]
No.

```
-- | Mode #PyLink [+ACfnt 7:5]
```

And the ban list is empty.

**Comment by TkTech** [comment]
Not pylink, but this is funny. A few dozen of these in the logs:

```
parsed_line(prefix='io.overdrive.pw', command='404', args=['Not-9da9', '#dev', 'Cannot send to channel (your message contained a censored word)'])
```

I currently see no errors for `#pylink` in the logs.

**Comment by GLolol** [comment]
I used `+g` to block labelling / unlabelling of issues (which I do very frequently), because I'm unable to turn those off explicitly in GitHub's settings without disabling announcements for issues being created. Ironically, `#dev` is the channel where Notifico actually works, and `#PyLink` simply gets ignored...

**Comment by GLolol** [comment]
`+g` is InspIRCd's IRCd-side message filters, by the way. I also use it as a workaround for #139 so it doesn't flood my channels!

```
10:24 -- #dev *The?Travis?CI?build?is?in?progress* GL 1447115458
10:24 -- #dev *labeled?issue*git.io* na.hub.overdrive.pw 1445131926
-- #dev :End of channel spamfilter list
```

**Comment by GLolol** [comment]
It's a new year! Now, Notifico is only sending messages into `#pylink` and ignoring `#dev` entirely...

**Comment by Dav1dde** [comment]
Are you sure it is not your network configuration, judging from the Website the only 2 channels which are configured for this network are yours.
That means notifico is using one connection and there should be no technical reason that announcing works for one but not the other. Reasons why it might not work, notifico can't even join the channel, it can't send messages because of channel modes etc.

**Comment by GLolol** [comment]
The bot is *present* in both channels and is able to speak in both. It's back to announcing commits to only `#dev`...

**Comment by GLolol** [comment]
Issue seems to have fixed itself, strange.
