### ISSUE TITLE
Branch deletion notifications not respecting branch filter

### ISSUE THREAD

**Issue by rom1504** [notifico/notifico#145]
For example

> 01:45 < Not-8b17> [flying-squid] rom1504 deleted branch greenkeeper-minecraft-data-1.2.4

Even though I set "master" in the branches option in notifico (and I set "only the push event" in the corresponding github hook)

**Comment by rom1504** [comment]
https://github.com/notifico/notifico/blob/9760b243b95ef51fdaee0dfe35638033558b580e/notifico/services/hooks/github.py#L705

https://github.com/notifico/notifico/blob/9760b243b95ef51fdaee0dfe35638033558b580e/notifico/services/hooks/github.py#L607

I guess https://github.com/notifico/notifico/blob/9760b243b95ef51fdaee0dfe35638033558b580e/notifico/services/hooks/github.py#L614 should probably be before the _create_non_commit_summary call

**Comment by Dav1dde** [comment]
Good catch! Want to open a pull request?

**Comment by rom1504** [comment]
I could try, but testing it would require me to actually build it and test it which doesn't seem obvious to do.

**Comment by TkTech** [comment]
Setup should take < 5 minutes and require 0 configuration (defaults are sufficient). Check the project README for the steps.

If you find particular areas too obtuse or lacking documentation I consider that a bug and will try to improve it.
