### ISSUE TITLE
Duplicate messages are sent if the entire organisation is webhooked

### ISSUE THREAD

**Issue by Teteros** [notifico/notifico#147]
I'm receiving a second notification for some events occurring in any of the organizations' repositories.
When deleting a branch or tag for example. Pushing is messaged only once, as expected.

Is it possible the bot reports once for the organization and once for the actual repository, hence the duplicate?
The organization hook is set to '*' (everything). Maybe some event is parsed twice I suppose?

Only the organisation is webhooked, the repositories are not.

**EDIT:**
Checking the webhook payloads for the org. I first see 'created' and then 'push' events are sent for the same branch which is likely the cause for `Teteros created branch X` appearing twice with different git.io URLs.

For the deleted tag one, this time it was 'delete' followed by 'push' event.

**Comment by Dav1dde** [comment]
This is known and not a bug, notifico simply forwards everything github sends. You can untick the create and delete messages in the webhook settings.  
![image](https://cloud.githubusercontent.com/assets/255721/13722668/972b52fa-e84d-11e5-8fac-d1a74670ba97.png)

**Comment by Teteros** [comment]
Done and working as intended. Thanks.
I've figured there would be a different message for 'create' and 'delete' to distinguish both from 'push', hence the issue.
