### ISSUE TITLE
Errors on n.tkte.ch

### ISSUE THREAD

**Issue by Changaco** [notifico/notifico#158]
Hi,

The TLS certificate on n.tkte.ch expired a while ago, and since yesterday GitHub notifications have begun to fail for us (response code is 500).

Are you aware of these issues? Do you need help or funding to maintain the service?

**Comment by Croydon** [comment]
I wrote an email a while ago and got no response. Makes me wonder if the host still gets maintained.

**Comment by Dav1dde** [comment]
It does, @TkTech is just pretty busy, best way to reach him is probably through here or the `#notifico` channel on freenode.

**Comment by Dav1dde** [comment]
Conversation from IRC:

```
<SinZ> [03:48:28] TkTech: earlier today some webhook messages to notifico got HTTP 500 while messages within seconds of that were fine. (It was doing status fine, but pull request and push failed)
<TkTech> [03:50:56] SinZ, SSL errors from git.io.
<TkTech> [03:51:29] Nothing I can do about git.io falling over
<SinZ> [03:52:41] fair enough, wasn't sure if some new update hit production and didn't affect status
```

Can't say if it was about this particular issue, but sounds like it.

**Comment by Changaco** [comment]
It seems to me that the solution to a TLS fail on git.io is to catch the corresponding exception here: https://github.com/notifico/notifico/blob/cdb2670454c5262aa87896cb73d2986cd8b06494/notifico/services/hooks/github.py#L848

**Comment by Changaco** [comment]
Also, I'm pretty sure that code is slower than it could be, because connection pooling isn't used (see https://github.com/kennethreitz/requests/issues/3445).

**Comment by Dav1dde** [comment]
Pull requests welcome.

**Comment by Changaco** [comment]
I'd be easier if I had a traceback, to know which exception is raised and should be caught when TLS fails.

**Comment by TkTech** [comment]
This is the relevant part of the traceback:

```
  File "notifico/services/hooks/github.py", line 520, in _handle_member
    url=GithubHook.shorten(json['member']['html_url']),
  File "notifico/services/hooks/github.py", line 740, in shorten
    }, timeout=4.0)
  File "requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "requests/sessions.py", line 354, in request
    resp = self.send(prep, **send_kwargs)
  File "requests/sessions.py", line 460, in send
    r = adapter.send(request, **kwargs)
  File "requests/adapters.py", line 250, in send
    raise SSLError(e)
SSLError: [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```

**Comment by simnalamburt** [comment]
I'm still receiving this error. Both TLS certificate error and 500 internal server error. Sadly, this issue is still being occurred.

<img src="https://cloud.githubusercontent.com/assets/4435445/20909747/d9dd868c-bba0-11e6-961d-e184568035d1.png" width=300>

<img src="https://cloud.githubusercontent.com/assets/4435445/20909750/dac0936e-bba0-11e6-8270-5941d115b61c.png" width=300>

**Comment by TkTech** [comment]
@simnalamburt Would you be able to send me an example payload causing the issue? tk@tkte.ch

**Comment by simnalamburt** [comment]
@TkTech No problem. Thank you for having continuous interest in this issue!

**Comment by simnalamburt** [comment]
I've sent it! Please feel free to request any further information about this issue. Thanks!

**Comment by Changaco** [comment]
Sorry about the delay in fixing this, here is the pull request: #159. I have other changes in mind that I'll try to push soon.

**Comment by TkTech** [comment]
@simnalamburt thank you, I believe I've resolved all the issues but would rather not deploy just before midnight :) I'll push and deploy tomorrow, there are actually several recent PRs missing from production.

SSL certificate errors will also get fixed tomorrow when I get the chance.

**Comment by simnalamburt** [comment]
@TkTech Thank you very much! I always use notifico useful. Thank you very much for managing such a good service.

**Comment by wodim** [comment]
(still 500ing)

**Comment by Wallbraker** [comment]
Ping?

**Comment by TkTech** [comment]
Let me know if you're still encountering errors, but as of now the hourly error rate is back down to 0.

**Comment by SinZ163** [comment]
My errors are now gone

**Comment by wodim** [comment]
It keeps failing for me.

**Comment by TkTech** [comment]
@wodim Just pushed a small fix for a new error, try it again if you could :)

**Comment by wodim** [comment]
Nothing.

**Comment by wodim** [comment]
Ah, now it works, thank you.

**Comment by Croydon** [comment]
Btw, @Changaco what exactly is the issue with git.io?

Not having any short URLs anymore is quite some spam in IRC.

**Comment by Changaco** [comment]
I don't know anymore than you do, but a quick web search on the error message in the traceback given above (`SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error`) suggests that the client (n.tkte.ch) and/or the server (git.io) is/are ill-configured, or using obsolete software.

I suggest you open a new issue.

(The non-shortened URLs haven't really bothered me, my screen is wide-enough for the notifications to still fit on one line.)

**Comment by TkTech** [comment]
The original problem was git.io disabling support for certain hashes. A broken version of OpenSSL "supported" the new preferred hash, but was broken, accepting it then failing instead of falling back. Downgrading to an older OpenSSL or upgrading to a newer OpenSSL resolves the SSL alerts.
