### ISSUE TITLE
Cannot create gitlab hook on n.tkte.ch

### ISSUE THREAD

**Issue by PolarizedIons** [notifico/notifico#169]
It is an option when running from source, but on http://n.tkte.ch Gitlab is not an option on the list 

![](http://image.prntscr.com/image/5fbe464b5b7d47e5b6c31ce9723091bb.png)

**Comment by Croydon** [comment]
@TkTech Hasn't updated the hosted version in quite some time. 
It shouldn't be much work, what is holding you off doing it @TkTech?
