### ISSUE TITLE
better domain name for the hosted service

### ISSUE THREAD

**Issue by ssbarnea** [notifico/notifico#180]
It would clearly help build more trust if **notifico** would run on a domain name cotaining notifico instead of its current cryptic name... which made me wonder about its future/safety initially.

**Comment by TkTech** [comment]
n.tkte.ch is my personal notifico instance. It was always intended for people to run their own. It's never been linked to by me or advertised/announced anywhere. However by word of mouth it's ended up getting quite a few users and I've kept it running for seven years.

It is not going anywhere, and is on a reserved instance prepaid for several years. But it will never leave n.tkte.ch.

**Comment by ssbarnea** [comment]
Thanks for clarifining, not really a big deal. I am sure that that there are lots of people really appreciating the effort invested in running it.
