### ISSUE TITLE
Support for RSS feed hooks

### ISSUE THREAD

**Issue by ssbarnea** [notifico/notifico#185]
It would be very useful to be able to add RSS based hooks as this would enable integration with a huge numeber of sites/services that do expose events as rss feeds.

One suck example is StackOverflow where anyone can use RSS feeds to get new questions on a specific tag.

By implementing this we can aboid the need to implement service specific hooks, this being more generic.

**Comment by TkTech** [comment]
Requires both polling and state tracking, both undesired in notifico. You can run your own simple bot like wiki.vg does to push an RSS feed to a webhook.
