### ISSUE TITLE
Password reset / mail issue?

### ISSUE THREAD

**Issue by silv3rr** [notifico/notifico#186]
Hi,
Trying to reset password (https://n.tkte.ch/u/forgot) but not getting an email on my GMail address.
Did get message "A reset email has been sent." Tried multiple times but got no mail (not in spam folder either).

**Comment by TkTech** [comment]
There was an issue with the old email provider. I've just changed it to use mailgun and resets should be functional again once DNS changes propagate (could be the next 10 minutes or 48 hours).

**Comment by silv3rr** [comment]
Seems it not working yet, tried a few times the past few days
