### ISSUE TITLE
WebHook support for gitlab.org

### ISSUE THREAD

**Issue by MrKeiKun** [notifico/notifico#29]
Example payload:

``` json
{
  "before": "95790bf891e76fee5e1747ab589903a6a1f80f22",
  "after": "da1560886d4f094c3e6c9ef40349f7d38b5d27d7",
  "ref": "refs/heads/master",
  "user_id": 4,
  "user_name": "John Smith",
  "repository": {
    "name": "Diaspora",
    "url": "git@localhost:diaspora.git",
    "description": "",
    "homepage": "http://localhost/diaspora",
  },
  "commits": [
    {
      "id": "b6568db1bc1dcd7f8b4d5a946b0b91f9dacd7327",
      "message": "Update Catalan translation to e38cb41.",
      "timestamp": "2011-12-12T14:27:31+02:00",
      "url": "http://localhost/diaspora/commits/b6568db1bc1dcd7f8b4d5a946b0b91f9dacd7327",
      "author": {
        "name": "Jordi Mallach",
        "email": "jordi@softcatala.org",
      }
    },
    // ...
    {
      "id": "da1560886d4f094c3e6c9ef40349f7d38b5d27d7",
      "message": "fixed readme",
      "timestamp": "2012-01-03T23:36:29+02:00",
      "url": "http://localhost/diaspora/commits/da1560886d4f094c3e6c9ef40349f7d38b5d27d7",
      "author": {
        "name": "GitLab dev user",
        "email": "gitlabdev@dv6700.(none)",
      },
    },
  ],
  "total_commits_count": 4,
};
```

**Comment by jameswritescode** [comment]
GitLab support would be great! Has there been any consideration for this since the issue opened?

**Comment by TkTech** [comment]
@jameswritescode I'm personally probably not going to add support, but would gladly merge it if it was contributed.

**Comment by Techman-** [comment]
@TkTech Can you consider this, please? GitLab.com is pretty nice compared to the likes of Bitbucket and it offers free private repos, which is nice.

**Comment by TkTech** [comment]
Notifico is open source, PRs accepted :)

**Comment by Dav1dde** [comment]
This should be very similiar to Github. Might even just work with the Github hooks, haven't really looked into the details. 

Could probably be done by inheriting from the Github hook and only implementing `handle_request`.

**Comment by Techman-** [comment]
No idea, but I would appreciate you looking into this. My other solution is GitLab--> Slack --> IRC and it's rather clunky.

**Comment by wookayin** [comment]
Great, it works nice. BTW, do you please plan to deploy this support into http://n.tkte.ch/? Thanks!

**Comment by Techman-** [comment]
Bump. @TkTech
