### ISSUE TITLE
IRC Notifications are not sent to irc.reening.nl

### ISSUE THREAD

**Issue by jk-5** [notifico/notifico#67]
I came across a very weird issue. Sometimes the bot just randomly decides to not join irc.reening.nl and all notifications are lost. GitHub tells me it deployed them properly and the notification count increases on the site. It worked for a long time, but then it stopped working for like a week and started working again. A week ago it stopped working again and i still have no result. I tried re-adding the channels, with no luck. I tested it on 3 different networks and they all work properly, except this one.

I don't know what the proper way is to repot this, so i'm just throwing this here. If you need additional information, either ask me here or on irc.freenode.net

**Comment by Aokromes** [comment]
There is any hope to force bot restart? It's annoying having to delete the configuration and add new config to make it to work again.

**Comment by GLolol** [comment]
@Aokromes :+1:

**Comment by TkTech** [comment]
See #120
